load('MSE_array.mat')
load('MSE_array_lin.mat')

 Z2 = MSE_array_lin;
 Z1 = MSE_array;
 
 yvec = [45 55 70 78 84 92 101 112 120 124];
 xvec = 1:5;
 
 YY = repmat(yvec',[1,5]);
 XX = repmat(xvec,[10,1]);
 
%  figure
%  surf(XX,YY,Z2)
 
 [x,y] = meshgrid(1:0.05:5,125:-1:45);
 z = griddata(XX,YY,Z1,x,y,'cubic');
 z2 = griddata(XX,YY,Z2,x,y,'cubic');


%CREATEFIGURE(XMatrix1, Y1, ZMatrix1, xdata1, ydata1, zdata1, zdata2)
%  XMATRIX1:  matrix of x data
%  Y1:  vector of y data
%  ZMATRIX1:  matrix of z data
%  XDATA1:  surface xdata
%  YDATA1:  surface ydata
%  ZDATA1:  surface zdata
%  ZDATA2:  surface zdata

%  Auto-generated by MATLAB on 24-Jul-2018 09:05:27

% Create figure
figure(6);
hold on
colormap(jet(256));

% Create axes
%axes1 = axes;
%hold(axes1,'on');

% Create multiple lines using matrix input to plot3
plot3(XX,YY,Z1,'Marker','pentagram','LineStyle','none',...
    'Color',[0 0 0]);

% Create multiple lines using matrix input to plot3
plot3(XX,YY,Z2,'Marker','pentagram','LineStyle','none',...
    'Color',[0 0 0]);

% Create surf
surf(x,y,z,'FaceLighting','gouraud','FaceAlpha',0.75,...
    'EdgeColor','none');

% Create light
light('Position',[3.80986660838158 1934.65809456995 8.54856928263046],...
    'Style','local');

% Create surf
surf(x,y,z2,'FaceLighting','gouraud','FaceAlpha',0.75,...
    'EdgeColor','none');

% Create light
light('Position',[3.80986660838158 1934.65809456995 9.70666416306887],...
    'Style','local');

% Create zlabel
zlabel('RMSE [cm cartilage]');

% Create ylabel
ylabel('SNR');

% Create xlabel
xlabel('# Energy Bins');

% Create title
title('Error Surface','FontName','Palatino');

%view(axes1,[-150.2 17.6]);
% Set the remaining axes properties
%set(axes1,'XTick',[1 2 3 4 5]);
